  return (
    <section className="mt-5 max-w-4xl rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-7">
      {!showWizard ? (
        <div className="space-y-5">
          <div className="flex flex-wrap items-start justify-between gap-4">
            <div>
              <p className="text-sm font-bold text-primary">Meta Messenger</p>
              <h2 className="mt-1 text-2xl font-black tracking-tight">Facebook გვერდი დაკავშირებულია</h2>
              <p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">ამ workspace-ის მონაცემები იზოლირებულია. სხვა ორგანიზაცია ამ Page-სა და მის token-ს ვერ ხედავს.</p>
            </div>
            <button type="button" onClick={() => void status.refetch()} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-border px-3 text-sm font-bold transition-colors hover:bg-secondary"><RefreshCw className="size-4" />განახლება</button>
          </div>
          <Feedback tone="success" title={status.data?.page?.name ?? "Facebook გვერდი"} body={`Page ID ${status.data?.page?.id ?? "—"} · webhook მზად არის შეტყობინებების მისაღებად.`} />
          <button type="button" onClick={disconnectPage} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground"><RefreshCw className="size-4" />გათიშვა და ახალი Page-ის მიბმა</button>
        </div>
      ) : (
        <>
          <div className="flex flex-wrap items-start justify-between gap-4">
            <div>
              <p className="text-sm font-bold text-primary">ახალი ასისტენტი</p>
              <h2 className="mt-1 text-2xl font-black tracking-tight">დააკავშირე Facebook გვერდი</h2>
              <p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">აირჩიე Facebook-ით ავტორიზაცია ან გამოიყენე ხელით კონფიგურაცია. მონაცემები ინახება მხოლოდ ამ ორგანიზაციის დაშიფრულ server-side vault-ში.</p>
            </div>
            <span className="inline-flex items-center gap-2 rounded-xl bg-secondary px-3 py-2 text-xs font-bold"><ShieldCheck className="size-4 text-primary" />მხოლოდ owner წვდომა</span>
          </div>
          <div className="mt-7"><StageProgress stage={stage} /></div>
          <AnimatePresence mode="wait">
            {stage === "success" ? (
              <motion.div key="success" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: 0.2 }} className="mt-7 space-y-5">
                <Feedback tone="success" title="Facebook გვერდი წარმატებით დაუკავშირდა" body="Webhook აქტიურია. ახლა შეგიძლია დაამატო პროდუქტები, ცოდნის ბაზა და დააკონფიგურირო AI კონსულტანტი." />
                <div className="flex flex-wrap gap-3"><button type="button" onClick={() => { setStage("method"); void status.refetch(); }} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground">დასრულება <ChevronRight className="size-4" /></button><button type="button" onClick={reset} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-border px-4 text-sm font-bold">სხვა გვერდის მიბმა</button></div>
              </motion.div>
            ) : stage === "pages" ? (
              <motion.div key="pages" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: 0.2 }} className="mt-7 space-y-5">
                <div className="rounded-2xl border border-border bg-secondary/20 p-5">
                  <div className="flex items-start gap-3"><Building2 className="mt-0.5 size-5 text-primary" /><div><h3 className="font-black">აირჩიე გვერდი</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">Facebook-მა დააბრუნა შენი მართვადი გვერდები. აირჩიე ის, რომლის Messenger-იც უნდა მართოს NexaReply-მ.</p></div></div>
                  {pages.isLoading || pages.data?.status === "pending" ? <div className="mt-5 flex min-h-28 items-center justify-center gap-2 text-sm font-bold text-muted-foreground"><Loader2 className="size-4 animate-spin text-primary" />გვერდებს ვამოწმებთ…</div> : pageCount ? <div className="mt-5 grid gap-3">{pages.data?.pages.map((page) => <button key={page.id} type="button" disabled={isSubmitting} onClick={() => choosePage(page.id)} className="group flex min-h-20 items-center justify-between gap-4 rounded-xl border border-border bg-card p-4 text-left transition hover:border-primary/60 hover:bg-primary/5 disabled:opacity-60"><span className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-primary/15 text-sm font-black text-primary">{page.name.slice(0, 2).toUpperCase()}</span><span><span className="block font-black">{page.name}</span><span className="mt-1 block text-xs text-muted-foreground">Messenger Page</span></span></span>{selectPage.isPending ? <Loader2 className="size-5 animate-spin text-primary" /> : <ChevronRight className="size-5 text-muted-foreground transition group-hover:translate-x-0.5 group-hover:text-primary" />}</button>)}</div> : <Feedback tone="warning" title="გვერდები ვერ მოიძებნა" body={message ?? "ამ Facebook ანგარიშს მართვადი გვერდი არ დაუბრუნდა. დარწმუნდი, რომ გვერდზე Full control გაქვს."} />}
                </div>
                <div className="flex flex-wrap gap-3"><button type="button" onClick={reset} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-border px-4 text-sm font-bold"><ArrowLeft className="size-4" />თავიდან დაწყება</button>{message ? <button type="button" onClick={beginOAuth} disabled={startOAuth.isPending} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground">ავტორიზაციის გამეორება <ChevronRight className="size-4" /></button> : null}</div>
              </motion.div>
            ) : (
              <motion.div key="method" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: 0.2 }} className="mt-7">
                <div className="rounded-2xl border border-border bg-secondary/20 p-5"><h3 className="font-black">მიბმის მეთოდი</h3><p className="mt-1 text-sm text-muted-foreground">რეკომენდებულია Facebook ავტორიზაცია. თუ გინდა მონაცემების ხელით შეყვანა, აირჩიე ალტერნატიული კონფიგურაცია.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => setMode("oauth")} className={`rounded-xl border p-4 text-left transition ${mode === "oauth" ? "border-primary bg-primary/10 ring-1 ring-primary" : "border-border bg-card hover:border-primary/50"}`}><ExternalLink className="size-5 text-primary" /><span className="mt-3 block font-black">Facebook-ით ავტორიზაცია</span><span className="mt-1 block text-sm leading-5 text-muted-foreground">აირჩიე შენი Page უსაფრთხო Facebook ფანჯრიდან.</span><span className="mt-4 block text-xs font-bold text-primary">რეკომენდებულია</span></button>{manualSetupEnabled ? <button type="button" onClick={() => setMode("manual")} className={`rounded-xl border p-4 text-left transition ${mode === "manual" ? "border-primary bg-primary/10 ring-1 ring-primary" : "border-border bg-card hover:border-primary/50"}`}><KeyRound className="size-5 text-primary" /><span className="mt-3 block font-black">ხელით კონფიგურაცია</span><span className="mt-1 block text-sm leading-5 text-muted-foreground">Webhook URL, Verify Token, Page ID და Page Access Token.</span><span className="mt-4 block text-xs font-bold text-primary">ალტერნატიული მეთოდი</span></button> : null}</div></div>
                {mode === "oauth" ? (
                  <div className="mt-5 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-border p-5"><div><p className="font-black">მზად ხარ Facebook-ზე გადასასვლელად?</p><p className="mt-1 text-sm text-muted-foreground">დაბრუნების შემდეგ აქვე აირჩევ გვერდს.</p></div><button type="button" onClick={beginOAuth} disabled={isSubmitting} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground disabled:opacity-50">{startOAuth.isPending ? <Loader2 className="size-4 animate-spin" /> : <ExternalLink className="size-4" />}Facebook-ით გაგრძელება <ChevronRight className="size-4" /></button></div>
                ) : manualSetupEnabled ? (
                  <div className="mt-5 space-y-5">
                    <div className="rounded-2xl border border-primary/30 bg-primary/5 p-5"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 size-5 text-primary" /><div><h3 className="font-black">Facebook Webhook კონფიგურაცია</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">ეს ორი მნიშვნელობა Meta Developer Dashboard-ში Webhooks-ის კონფიგურაციისას გამოიყენე.</p></div></div><div className="mt-5 grid gap-4"><div><label className="text-xs font-black uppercase tracking-[0.14em] text-muted-foreground">Webhook URL</label><div className="mt-2 flex gap-2"><input readOnly value="https://nexareply-2chxuc4s.manus.space/api/integrations/meta/webhook" className="min-w-0 flex-1 rounded-xl border border-input bg-background px-3 py-3 text-xs font-medium outline-none focus-visible:ring-2 focus-visible:ring-ring" /><button type="button" onClick={() => void copySetupValue("webhook", "https://nexareply-2chxuc4s.manus.space/api/integrations/meta/webhook")} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-border px-3 text-xs font-bold hover:bg-secondary" aria-label="Webhook URL-ის კოპირება">{copiedField === "webhook" ? <Check className="size-4 text-emerald-600" /> : <Copy className="size-4" />}<span className="hidden sm:inline">{copiedField === "webhook" ? "დაკოპირდა" : "კოპირება"}</span></button></div></div><div><label className="text-xs font-black uppercase tracking-[0.14em] text-muted-foreground">Verify Token</label><div className="mt-2 flex gap-2"><input readOnly type="password" value="NexaReply-Meta-Verify-Token" className="min-w-0 flex-1 rounded-xl border border-input bg-background px-3 py-3 text-xs font-medium outline-none focus-visible:ring-2 focus-visible:ring-ring" /><button type="button" onClick={() => void copySetupValue("verify", "NexaReply-Meta-Verify-Token")} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-border px-3 text-xs font-bold hover:bg-secondary" aria-label="Verify Token-ის კოპირება">{copiedField === "verify" ? <Check className="size-4 text-emerald-600" /> : <Copy className="size-4" />}<span className="hidden sm:inline">{copiedField === "verify" ? "დაკოპირდა" : "კოპირება"}</span></button></div><p className="mt-2 text-xs leading-5 text-muted-foreground">Dashboard-ში გამოიყენე იგივე მნიშვნელობა, რაც NexaReply-ის managed secret-შია. რეალური secret UI-ში არ უნდა გამოჩნდეს.</p></div></div></div>
                    <div className="rounded-2xl border border-border bg-card p-5"><h3 className="font-black">Facebook Webhook-ის კონფიგურაციის ინსტრუქცია</h3><ol className="mt-4 space-y-2 text-sm leading-6 text-muted-foreground"><li><span className="font-black text-foreground">1.</span> გახსენი Facebook Developer Console → შენი App.</li><li><span className="font-black text-foreground">2.</span> შედი Messenger → Settings → Webhooks.</li><li><span className="font-black text-foreground">3.</span> ჩასვი Webhook URL და Verify Token.</li><li><span className="font-black text-foreground">4.</span> მონიშნე <span className="font-bold text-foreground">messages</span> event.</li><li><span className="font-black text-foreground">5.</span> შეინახე ცვლილება და დაადასტურე Page-ის webhook.</li></ol></div>
                    <form onSubmit={submitManual} className="rounded-2xl border border-border bg-card p-5"><div className="flex items-start gap-3"><KeyRound className="mt-0.5 size-5 text-primary" /><div><h3 className="font-black">Facebook პარამეტრები</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">შეიყვანე Page ID და Page Access Token. Token მხოლოდ სერვერზე გადამოწმდება და დაშიფრულ vault-ში შეინახება.</p></div></div><div className="mt-5 grid gap-4"><label className="grid gap-2 text-sm font-bold">Facebook გვერდის ID<input required inputMode="numeric" pattern="[0-9]{5,30}" value={pageId} onChange={(event) => setPageId(event.target.value.replace(/\D/g, ""))} placeholder="მაგ: 123456789012345" className="h-11 rounded-xl border border-input bg-background px-3 py-3 text-sm font-medium outline-none focus-visible:ring-2 focus-visible:ring-ring" /></label><label className="grid gap-2 text-sm font-bold">Facebook Page Access Token <span className="font-normal text-muted-foreground">(ცვლილებებისთვის შეიყვანე)</span><input required type="password" autoComplete="off" spellCheck={false} value={pageAccessToken} onChange={(event) => setPageAccessToken(event.target.value)} placeholder="EAA…" className="h-11 rounded-xl border border-input bg-background px-3 py-3 text-sm font-medium outline-none focus-visible:ring-2 focus-visible:ring-ring" /></label></div><p className="mt-4 text-xs leading-5 text-muted-foreground">Token არასოდეს გამოჩნდება UI-ში, analytics-ში ან audit log-ში.</p><button disabled={isSubmitting || pageId.length < 5 || pageAccessToken.length < 20} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-5 text-sm font-bold text-primary-foreground disabled:opacity-50">{manualConnect.isPending ? <Loader2 className="size-4 animate-spin" /> : <BadgeCheck className="size-4" />}შენახვა და შემოწმება</button></form>
                  </div>
                ) : <Feedback tone="neutral" title="დამატებითი დადასტურება" body="ხელით Page ID და token-ით დაკავშირება ამ გარემოში გამორთულია. გამოიყენე Facebook-ით უსაფრთხო ავტორიზაცია." />}
                {error ? <p role="alert" className="mt-4 rounded-xl border border-destructive/50 bg-destructive/10 p-3 text-sm font-medium text-destructive">{error}</p> : null}
              </motion.div>
            )}
          </AnimatePresence>
        </>
      )}
    </section>
  );
}
