import { trpc } from "@/lib/trpc";
import { BookOpenCheck, FileText, Loader2, Plus, Search, Trash2, X } from "lucide-react";
import { useMemo, useState } from "react";

export default function KnowledgeView() {
  const utils = trpc.useUtils();
  const [query, setQuery] = useState("");
  const [showCreate, setShowCreate] = useState(false);
  const [title, setTitle] = useState("");
  const [body, setBody] = useState("");
  const factsQuery = trpc.nexareply.demo.data.knowledge.list.useQuery();
  const createFact = trpc.nexareply.demo.data.knowledge.create.useMutation();
  const archiveFact = trpc.nexareply.demo.data.knowledge.archive.useMutation();
  const facts = useMemo(() => (factsQuery.data ?? []).filter((fact) => `${fact.title} ${fact.body}`.toLocaleLowerCase("ka-GE").includes(query.toLocaleLowerCase("ka-GE"))), [factsQuery.data, query]);
  const refresh = () => utils.nexareply.demo.data.knowledge.list.invalidate();
  const addFact = () => createFact.mutate({ title, body }, { onSuccess: () => { setTitle(""); setBody(""); setShowCreate(false); void refresh(); } });
  return <div className="space-y-6"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold text-primary">სანდოობის წყარო</p><h1 className="mt-1 text-2xl font-bold tracking-tight md:text-3xl">ცოდნის ბაზა</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">სტრუქტურირებული ფაქტები persistent ორგანიზაციის მონაცემებში ინახება და Demo AI მხოლოდ ამ წყაროს ეყრდნობა.</p></div><button type="button" onClick={() => setShowCreate((value) => !value)} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><Plus className="size-4" />ფაქტის დამატება</button></div>
  {showCreate && <section className="rounded-2xl border border-primary/20 bg-primary/[0.035] p-5"><div className="flex items-start justify-between"><div><h2 className="font-bold">ახალი ცოდნის ფაქტი</h2><p className="mt-1 text-sm text-muted-foreground">მიუთითეთ მხოლოდ დადასტურებული ბიზნეს ინფორმაცია.</p></div><button type="button" onClick={() => setShowCreate(false)} className="grid size-9 place-items-center rounded-lg hover:bg-accent" aria-label="დახურვა"><X className="size-4" /></button></div><label className="mt-4 block text-xs font-semibold text-muted-foreground">სათაური<input value={title} onChange={(event) => setTitle(event.target.value)} className="mt-1 h-10 w-full rounded-lg border border-input bg-background px-3 text-sm text-foreground outline-none focus-visible:ring-2 focus-visible:ring-ring" /></label><label className="mt-3 block text-xs font-semibold text-muted-foreground">დადასტურებული ინფორმაცია<textarea value={body} onChange={(event) => setBody(event.target.value)} className="mt-1 min-h-24 w-full rounded-lg border border-input bg-background p-3 text-sm text-foreground outline-none focus-visible:ring-2 focus-visible:ring-ring" /></label><button type="button" onClick={addFact} disabled={!title.trim() || !body.trim() || createFact.isPending} className="mt-4 inline-flex min-h-10 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground disabled:opacity-50">{createFact.isPending && <Loader2 className="size-4 animate-spin" />}შენახვა</button></section>}
  <div className="relative max-w-xl"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="h-11 w-full rounded-xl border border-input bg-card pl-9 pr-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" placeholder="მოძებნეთ წესები და ფაქტები" aria-label="ცოდნის ბაზის ძიება" /></div><div className="grid gap-4 lg:grid-cols-[1.35fr_0.65fr]"><section className="grid gap-3 sm:grid-cols-2">{factsQuery.isLoading ? <div className="col-span-2 grid min-h-44 place-items-center rounded-2xl border border-border bg-card"><Loader2 className="size-5 animate-spin text-primary" /></div> : facts.map((fact) => <article key={fact.id} className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#E7F8FC] text-[#0E7490] dark:bg-[#0E7490]/30 dark:text-[#A5F3FC]"><BookOpenCheck className="size-5" /></span><button type="button" onClick={() => archiveFact.mutate({ id: fact.id }, { onSuccess: () => void refresh() })} className="grid size-8 place-items-center rounded-lg text-muted-foreground hover:bg-[#FDECEC] hover:text-[#991B1B]" aria-label="ფაქტის არქივირება"><Trash2 className="size-4" /></button></div><h2 className="mt-4 text-base font-bold">{fact.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{fact.body}</p><p className="mt-4 text-xs font-semibold text-[#166534] dark:text-[#86EFAC]">ხელმისაწვდომია AI პასუხისთვის</p></article>)}</section><aside className="rounded-2xl border border-border bg-card p-5 shadow-sm"><FileText className="size-5 text-primary" /><h2 className="mt-4 font-bold">დოკუმენტები</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">PDF/TXT policy ფაილების bytes production-ში ინახება უსაფრთხო storage-ში; ამ ეტაპზე schema და metadata boundary მზადაა, ხოლო file-upload UI ცალკე ინტეგრაციას საჭიროებს.</p><div className="mt-5 rounded-xl border border-dashed border-border bg-muted/40 p-4 text-center"><p className="text-sm font-semibold">დოკუმენტის ატვირთვა მალე დაემატება</p><p className="mt-1 text-xs leading-5 text-muted-foreground">ცოდნის ტექსტური ფაქტები უკვე persistent და მოქმედია.</p></div></aside></div></div>;
}
