import { demoKnowledgeFacts } from "@/lib/demo-data";
import { BookOpenCheck, FileText, Plus, Search } from "lucide-react";
import { useMemo, useState } from "react";

export default function KnowledgeView() {
  const [query, setQuery] = useState("");
  const facts = useMemo(() => demoKnowledgeFacts.filter((fact) => `${fact.title} ${fact.body}`.toLocaleLowerCase("ka-GE").includes(query.toLocaleLowerCase("ka-GE"))), [query]);
  return <div className="space-y-6"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold text-primary">სანდოობის წყარო</p><h1 className="mt-1 text-2xl font-bold tracking-tight md:text-3xl">ცოდნის ბაზა</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">სტრუქტურირებული ფაქტები ეხმარება AI-ს, რომ არ გამოიგონოს პირობები.</p></div><button type="button" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><Plus className="size-4" />ფაქტის დამატება</button></div><div className="relative max-w-xl"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="h-11 w-full rounded-xl border border-input bg-card pl-9 pr-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" placeholder="მოძებნეთ წესები და ფაქტები" aria-label="ცოდნის ბაზის ძიება" /></div><div className="grid gap-4 lg:grid-cols-[1.35fr_0.65fr]"><section className="grid gap-3 sm:grid-cols-2">{facts.map((fact) => <article key={fact.title} className="rounded-2xl border border-border bg-card p-5 shadow-sm"><span className="grid size-10 place-items-center rounded-xl bg-[#E7F8FC] text-[#0E7490] dark:bg-[#0E7490]/30 dark:text-[#A5F3FC]"><BookOpenCheck className="size-5" /></span><h2 className="mt-4 text-base font-bold">{fact.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{fact.body}</p><p className="mt-4 text-xs font-semibold text-[#166534] dark:text-[#86EFAC]">ხელმისაწვდომია AI პასუხისთვის</p></article>)}</section><aside className="rounded-2xl border border-border bg-card p-5 shadow-sm"><FileText className="size-5 text-primary" /><h2 className="mt-4 font-bold">დოკუმენტები</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">PDF/TXT policy ფაილები რეალურ workspace-ში ინახება უსაფრთხო storage-ში. ეს Demo Mode მხოლოდ workflow-ს აჩვენებს.</p><div className="mt-5 rounded-xl border border-dashed border-border bg-muted/40 p-4 text-center"><p className="text-sm font-semibold">ჯერ დოკუმენტი არ არის</p><p className="mt-1 text-xs leading-5 text-muted-foreground">ატვირთეთ policy ფაილი ცოდნის გასაფართოებლად.</p></div></aside></div></div>;
}
