import { trpc } from "@/lib/trpc";
import { BellRing, Check, CircleAlert, Clock3, Loader2, MessageSquareText } from "lucide-react";

const iconFor = (type: "human_takeover" | "high_priority_lead" | "needs_human" | "ai_paused") => type === "needs_human" ? "alert" : type === "high_priority_lead" ? "lead" : "info";

export default function NotificationsView() {
  const utils = trpc.useUtils();
  const list = trpc.nexareply.demo.data.notifications.list.useQuery();
  const markRead = trpc.nexareply.demo.data.notifications.markRead.useMutation();
  const items = list.data ?? [];
  const unread = items.filter((item) => !item.readAt).length;
  const refresh = () => utils.nexareply.demo.data.notifications.list.invalidate();
  const markAll = () => markRead.mutate({}, { onSuccess: () => void refresh() });
  return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-primary">Owner alerts</p><h1 className="mt-1 text-2xl font-bold tracking-tight md:text-3xl">შეტყობინებები</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Human takeover და უცნობი კითხვა ქმნის idempotent in-app notification-ს. Email/Telegram dispatch რეალური credentials-ისა და notification adapter-ის ჩართვის შემდეგ დაემატება.</p></div><button type="button" onClick={markAll} disabled={!unread || markRead.isPending} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-xl border border-border bg-card px-3 text-xs font-semibold hover:bg-accent disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">{markRead.isPending ? <Loader2 className="size-3.5 animate-spin" /> : <Check className="size-3.5" />}ყველას მონიშვნა</button></div><section className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm">{list.isLoading ? <div className="grid min-h-48 place-items-center"><Loader2 className="size-5 animate-spin text-primary" /></div> : items.map((item) => { const kind = iconFor(item.type); return <article key={item.id} className={`flex gap-4 border-b border-border p-5 last:border-b-0 ${!item.readAt ? "bg-primary/[0.035]" : ""}`}><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${kind === "alert" ? "bg-[#FDECEC] text-[#991B1B] dark:bg-[#991B1B]/30 dark:text-[#FECACA]" : kind === "lead" ? "bg-[#E9F8EF] text-[#166534] dark:bg-[#166534]/30 dark:text-[#86EFAC]" : "bg-[#E7F8FC] text-[#0E7490] dark:bg-[#0E7490]/30 dark:text-[#A5F3FC]"}`}>{kind === "alert" ? <CircleAlert className="size-5" /> : kind === "lead" ? <BellRing className="size-5" /> : <MessageSquareText className="size-5" />}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-bold">{item.title}</h2>{!item.readAt && <span className="size-2 rounded-full bg-primary" aria-label="წაუკითხავი" />}</div><p className="mt-1 text-sm leading-6 text-muted-foreground">{item.body}</p><p className="mt-2 inline-flex items-center gap-1.5 text-xs text-muted-foreground"><Clock3 className="size-3.5" />{new Date(item.createdAt).toLocaleString("ka-GE")}</p></div><button type="button" onClick={() => markRead.mutate({ ids: [item.id] }, { onSuccess: () => void refresh() })} disabled={Boolean(item.readAt) || markRead.isPending} className="self-start rounded-lg px-2 py-1 text-xs font-semibold text-primary hover:bg-primary/10 disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">ნახვა</button></article>; })}{!list.isLoading && !items.length && <div className="p-10 text-center text-sm text-muted-foreground">შეტყობინება ჯერ არ არის.</div>}</section></div>;
}
