import { BellRing, Check, CircleAlert, Clock3, MessageSquareText } from "lucide-react";
import { useState } from "react";

const initialNotifications = [
  { id: "n1", title: "ოპერატორის ჩართვა საჭიროა", text: "გიორგი კაპანაძეს trade-in შეფასებაზე სჭირდება ზუსტი პასუხი.", time: "4 წუთის წინ", kind: "alert", unread: true },
  { id: "n2", title: "მაღალი პრიორიტეტის ლიდი", text: "ანა მჭედლიძე დაინტერესებულია iPhone 16 Pro Max-ით და 0%-იანი განვადებით.", time: "ახლახან", kind: "lead", unread: true },
  { id: "n3", title: "AI პასუხი შეჩერებულია", text: "სალომე ბერიძის საუბარი ხელით მართვაზეა გადაცემული.", time: "8 წუთის წინ", kind: "info", unread: false },
];

export default function NotificationsView() {
  const [items, setItems] = useState(initialNotifications);
  const unread = items.filter((item) => item.unread).length;
  const markAll = () => setItems((current) => current.map((item) => ({ ...item, unread: false })));
  return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-primary">Owner alerts</p><h1 className="mt-1 text-2xl font-bold tracking-tight md:text-3xl">შეტყობინებები</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Demo Mode აჩვენებს in-app alert-ს იმ workflow-ებისთვის, რომლებიც რეალურ გარემოში email ან Telegram დახმარებითაც შეიძლება მივიდეს მფლობელამდე.</p></div><button type="button" onClick={markAll} disabled={!unread} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-xl border border-border bg-card px-3 text-xs font-semibold hover:bg-accent disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><Check className="size-3.5" />ყველას მონიშვნა</button></div><section className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm">{items.map((item) => <article key={item.id} className={`flex gap-4 border-b border-border p-5 last:border-b-0 ${item.unread ? "bg-primary/[0.035]" : ""}`}><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${item.kind === "alert" ? "bg-[#FDECEC] text-[#991B1B] dark:bg-[#991B1B]/30 dark:text-[#FECACA]" : item.kind === "lead" ? "bg-[#E9F8EF] text-[#166534] dark:bg-[#166534]/30 dark:text-[#86EFAC]" : "bg-[#E7F8FC] text-[#0E7490] dark:bg-[#0E7490]/30 dark:text-[#A5F3FC]"}`}>{item.kind === "alert" ? <CircleAlert className="size-5" /> : item.kind === "lead" ? <BellRing className="size-5" /> : <MessageSquareText className="size-5" />}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-bold">{item.title}</h2>{item.unread && <span className="size-2 rounded-full bg-primary" aria-label="წაუკითხავი" />}</div><p className="mt-1 text-sm leading-6 text-muted-foreground">{item.text}</p><p className="mt-2 inline-flex items-center gap-1.5 text-xs text-muted-foreground"><Clock3 className="size-3.5" />{item.time}</p></div><button type="button" onClick={() => setItems((current) => current.map((notification) => notification.id === item.id ? { ...notification, unread: false } : notification))} className="self-start rounded-lg px-2 py-1 text-xs font-semibold text-primary hover:bg-primary/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">ნახვა</button></article>)}</section></div>;
}
